# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_engine_db
spring.datasource.username=root
spring.datasource.password=Madhu2924

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App Port
server.port=8081
# JWT Secret
jwt.secret=quizEngineSecretKey2024SuperSecure
jwt.expiration=86400000